name: release
on:
  workflow_run:
    workflows: [build]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Set GOLANG_VERSION
        run: |
          echo "GOLANG_VERSION=$(go version | awk '{ print $3 }')" >> $GITHUB_ENV
      - name: Tagged Release
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --debug --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
