project_name: sctl
before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -w
  - -X github.com/vapor-ware/sctl/version.BuildDate={{ .Date }}
  - -X github.com/vapor-ware/sctl/version.Commit={{ .ShortCommit }}
  - -X github.com/vapor-ware/sctl/version.Tag={{ .Tag }}
  - -X github.com/vapor-ware/sctl/version.Version={{ .Version }}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
release:
  github:
    owner: vapor-ware
    name: sctl
  draft: false
  prerelease: auto
  name_template: "{{ .Version }}"
dockers:
- goos: linux
  goarch: amd64
  binaries:
    - sctl
  image_templates:
    - vaporio/sctl:{{ .Tag }}
    - vaporio/sctl:{{ .Major }}
    - vaporio/sctl:latest
brews:
- name: github
  tap:
    owner: vapor-ware
    name: homebrew-formula
  commit_author:
    name: vio-bot
    email: 'marco+viogh@vapor.io'
  homepage: 'https://github.com/vapor-ware/sctl'
  description: 'Manage secrets on Google Cloud Platform with KMS and state files'
  test: |
    system "#{bin}/sctl --version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
